package com.cesarwillymc.mbcgroup.util.constants

const val EMPTY_STRING = ""
const val ZERO = 0
const val ZERO_D = 0.0
const val ZERO_F = 0f
const val ONE = 1
const val ONE_F = 1f
const val FIVE = 5
const val FRACTION_10 = 0.1f
const val FRACTION_20 = 0.2f
const val FRACTION_30 = 0.3f
const val FRACTION_40 = 0.4f
const val FRACTION_50 = 0.5f
const val FRACTION_70 = 0.7f
const val FRACTION_80 = 0.8f
const val FRACTION_90 = 0.9f
const val ALPHA_BACKGROUND = 0.6f
const val TWO = 2
const val TWO_F = 2f
const val DELAY_700 = 700L
const val DELAY_1000 = 1000L
const val DELAY_3000 = 3000
const val DELAY_2500 = 2000L
const val MIN_SEARCH_CHARACTERS = 3
const val FORMAT_DEEPLINK = "%s%s"
const val FORMAT_ONLY_US = "%s,US"
const val DEFAULT_FORMAT = "01d"
const val LOG_DATA = "ERROR_DATA"
const val LOG_DOMAIN = "ERROR_DOMAIN"
const val UTF_8 ="UTF_8"
const val FORMAT_HOUR = "hh:mm a"
const val FORMAT_TIME_ZONE = "America/Chicago"
