name: Generate Debug

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      groupTester:
        description: 'Testers'
        required: true
        default: 'qa'
        type: choice
        options:
          - all
          - qa
          - production
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  generation:
    runs-on: ubuntu-latest
    env:
      VALUE_DATA: |
        if [[ "${{ inputs.buildType }}" == "debug" ]]; then
          echo "Debug"
        else
          echo "Release"
        fi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configuration Local.properties
        env:
          SHARED_PREFERENCES_NAME: ${{ secrets.SHARED_PREFERENCES_NAME }}
          BASE_URL: ${{ secrets.BASE_URL }}
          BASE_URL_GQL: ${{ secrets.BASE_URL_GQL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          echo "SHARED_PREFERENCES_NAME=$SHARED_PREFERENCES_NAME" >> local.properties
          echo "BASE_URL=$BASE_URL" >> local.properties
          echo "BASE_URL_GQL=$BASE_URL_GQL" >> local.properties
          echo "CLIENT_ID=$CLIENT_ID" >> local.properties
          echo "CLIENT_SECRET=$CLIENT_SECRET" >> local.properties

      - name: Execute validations
        run: ./gradlew executeValidations
      - name: Build App
        run: ./gradlew assemble$VALUE_DATA
        env:
          DEBUG_KEY_PASSWORD: ${{ secrets.DEBUG_KEY_PASSWORD }}
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.app_id_${{ inputs.buildType }}}}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: ${{ inputs.groupTester }}
          file: app/build/outputs/apk/${{ inputs.buildType }}/app-${{ inputs.buildType }}.apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ inputs.buildType }}
          path: app/build/outputs/apk/${{ inputs.buildType }}/app-${{ inputs.buildType }}.apk
