name: Generate Debug

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configuration Local.properties
        env:
          SHARED_PREFERENCES_NAME: ${{ secrets.SHARED_PREFERENCES_NAME }}
          BASE_URL: ${{ secrets.BASE_URL }}
          BASE_URL_GQL: ${{ secrets.BASE_URL_GQL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          echo "SHARED_PREFERENCES_NAME=$SHARED_PREFERENCES_NAME" >> local.properties
          echo "BASE_URL=BASE_URL" >> local.properties
          echo "BASE_URL_GQL=BASE_URL_GQL" >> local.properties
          echo "CLIENT_ID=CLIENT_ID" >> local.properties
          echo "CLIENT_SECRET=CLIENT_SECRET" >> local.properties

      - name: Execute validations
        run: ./gradlew executeValidations
      - name: Build App
        run: ./gradlew assembleDebug appDistributionUploadDebug
        env:
          DEBUG_KEY_PASSWORD: ${{ secrets.DEBUG_KEY_PASSWORD }}
          TESTERS_GROUP: ${{ secrets.TESTERS_GROUP }}
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
